routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::group(['middleware' => ['web']], function() {
    Route::resource('blog','BlogController');

});

Route::get('/report', 'BlogController@report');

Route::group(['middleware' => ['web']], function() {
    Route::resource('client','ClientController');
});
Route::group(['middleware' => ['web']], function() {
    Route::resource('newclient','NewclientController');
});


Route::get('image-upload','ImageController@imageUpload');
Route::post('image-upload','ImageController@imageUploadPost');

app/Blog.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    protected $table ='blog_post';
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use App\Blog;

class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //show Data
        //$blogs = Blog::all();
        //$blogs =DB::table('blog_post')->paginate(5);
       // $blogs = Blog::paginate(5);
        //return view('blog.index',['blogs'=>$blogs]);
        $search = \Request::get('search');
        $blogs = Blog::where('title','like','%'.$search.'%')->orderBy('id')->paginate(6);
        return view('blog.index',['blogs' => $blogs]);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('blog.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // we will create validation function here
        $this->validate($request,[
            'title'=> 'required',
            'description' => 'required',
        ]);

        $blog = new Blog;
        $blog->title = $request->title;
        $blog->description = $request->description;


        $file = $request->file('images');
        $fileName = $file->getClientOriginalName();
        $request->file('images')->move("image/",$fileName);
        $blog->images = $fileName;
        // save all data
        $blog->save();
        //redirect page after save data
        return redirect('blog')->with('message','data hasbeen updated!');
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $blog = Blog::find($id);

        return view('blog.show')->with('blog',$blog);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $blog = Blog::findOrFail($id);
        return view('blog.edit',compact('blog'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // validation
        $this->validate($request,[
            'title'=> 'required',
            'description' => 'required',
        ]);

        $blog = Blog::findOrFail($id);
        $blog->title = $request->title;
        $blog->description = $request->description;
        $blog->save();
        session()->flash('massage','Update Successfully');

        return redirect()->route('blog.index');
            //->with('alert-success','Data Has been Saved!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //DELETE DATA
        $blog = Blog::findOrFail($id);
        $blog->delete();
        return redirect()->route('blog.index')->with('alert-success','Data Has Been Deleted!');

    }




}

resources/views/blog/create.blade.php
@extends('master')
@section('content')
    <h2>Add new post</h2>


    <form class="" action="/blog" method="post" enctype="multipart/form-data">
        <fieldset>
            <legend> Form</legend>
        <input type="text" name="title" value="" placeholder="this is title"><br>
        {{ ($errors->has('title')) ? $errors->first('title') : '' }} <br>
        <textarea name="description" rows="3" cols="22" placeholder="this is description"></textarea><br>
        {{ ($errors->has('description')) ? $errors->first('description') : '' }} <br>
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <img src="http://placehold.it/100x100" id="showimages" style="max-width:200px;max-height:200px;float:left;"/>
        <div class="row">
            <div class="col-md-12">
                <input type="file" id="inputimages" name="images">
            </div>
        </div>
            <br>
        <div class="col-md-12">
            <button type="submit" class="btn btn-primary pull-left" value="post">
                Submit
            </button>
            <a href="{{(route('blog.index'))}}" class="btn btn-success pull-left">Return</a><br>
        </div>
        </fieldset>
    </form>


@stop

resources/views/blog/details.blade.php
@extends('master')
@section('content')
    <div class="form-group row add">
        <div class="col-md-6">

        </div>

    </div>
    <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
            <input type="text" name="search" class="form-control" placeholder="search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
    </form>
    <div class="row">
        <h3 style="text-align: center">Blog Information</h3>
        <table class="table table-striped">
            <tr>
                <th> No.</th>
                <th> Title</th>
                <th> Description</th>
                <th> Action</th>
            </tr>
            <a href="{{(route('blog.create'))}}" class="btn btn-info pull-left">Create New Data</a><br>
            <?php $no=1;?>
            @foreach($blogs as $blog)
                <tr>
                    <td>{{$no++}}</td>
                    <td>{{$blog->title}}</td>
                    <td>{{$blog->description}}</td>
                    <td>
                        <form class="" action="{{route('blog.destroy',$blog->id)}}" method="post">
                            <input type="hidden" name="_method" value="delete">
                            <input type="hidden" name="_token" value="{{csrf_token()}}">
                            <a href="{{route('blog.show',$blog->id)}}" class="btn btn-primary">Show</a>
                            <a href="{{route('blog.edit',$blog->id)}}" class="btn btn-primary">Edit</a>


                            <input type="submit" class="btn btn-danger" onclick="return confirm('Are you sure to delete this data');" name="name" value="delete">



                        </form>
                    </td>
                </tr>
            @endforeach

        </table>
    </div>
    {!! $blogs->links() !!}
@stop

resources/views/blog/edit.blade.php
@extends('master')
@section('content')
    <div class="row">
        <div class="col-md-12">

        </div>
    </div>
    <div class="row">


        <h3 style="text-align: center">Edit Data</h3>
        <form class="" action="{{route('blog.update',$blog->id)}}" method="post">
            <input name="_method" type="hidden" value="PATCH">
            {{csrf_field()}}
            <h4>Title</h4>
            <div class="form-group{{ ($errors->has('title')) ? $errors->first('title') : '' }}">
                <input type="text" name="title" class="form-control" placeholder="Enter Title Here" value="{{$blog->title}}">
                {!! $errors->first('title','<p class="help-block">:message</p>') !!}
            </div>
            <h4>Description</h4>
            <div class="form-group{{ ($errors->has('description')) ? $errors->first('title') : '' }}">
                <input type="text" name="description" class="form-control" placeholder="Enter Description Here" value="{{$blog->description}}">
                {!! $errors->first('description','<p class="help-block">:message</p>') !!}
            </div>

            <div class="form-group">
                <input type="submit" class="btn btn-primary" value="save">
                <a href="{{(route('blog.index'))}}" class="btn btn-info pull-left">Return</a><br>

            </div>
        </form>
    </div>
@stop

resources/views/blog/index.blade.php
@extends('master')
@section('content')


    <div class="form-group row add">
        <div class="col-md-6">
      @if(session()->has('massage'))
          <h1 class=" alert alert-success">{{session()->get('massage')}}</h1>

            @endif
        </div>

</div>

    <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
            <input type="text" name="search" class="form-control" placeholder="search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
    </form>
<div class="row">
      <h3 style="text-align: center">Blog Information</h3>
    <table class="table table-striped">
<tr>
    <th> No.</th>
    <th> Title</th>
    <th> Description</th>
    <th> Images</th>
    <th> Action</th>
</tr>
        <a href="{{(route('blog.create'))}}" class="btn btn-info pull-left">Create New Data</a><br>
        <?php $no=1;?>
        @foreach($blogs as $blog)
            <tr>
                <td>{{$no++}}</td>
                <td>{{$blog->title}}</td>
                <td>{{$blog->description}}</td>
                <td>{{$blog->images}}</td>
                <td>
                <form class="" action="{{route('blog.destroy',$blog->id)}}" method="post">
                    <input type="hidden" name="_method" value="delete">
                    <input type="hidden" name="_token" value="{{csrf_token()}}">
                    <a href="{{route('blog.show',$blog->id)}}" class="btn btn-primary">Show</a>
                    <a href="{{route('blog.edit',$blog->id)}}" class="btn btn-primary">Edit</a>


                    <input type="submit" class="btn btn-danger" onclick="return confirm('Are you sure to delete this data');" name="name" value="delete">



                </form>
                </td>
            </tr>
        @endforeach

    </table>

</div>

{!! $blogs->links() !!}

    @stop

resources/views/blog/report.blade.php
@extends('master')
@section('content')
    <div class="form-group row add">
        <div class="col-md-6">

        </div>

    </div>
    <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
            <input type="text" name="search" class="form-control" placeholder="search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
    </form>
    <div class="row">
        <h3 style="text-align: center">Blog Information</h3>
        <table class="table table-striped">
            <tr>
                <th> No.</th>
                <th> Title</th>
                <th> Description</th>
                <th> Action</th>
            </tr>
            <a href="{{(route('blog.create'))}}" class="btn btn-info pull-left">Create New Data</a><br>
            <?php $no=1;?>
            @foreach($blogs as $blog)
                <tr>
                    <td>{{$no++}}</td>
                    <td>{{$blog->title}}</td>
                    <td>{{$blog->description}}</td>
                    <td>
                        <form class="" action="{{route('blog.destroy',$blog->id)}}" method="post">
                            <input type="hidden" name="_method" value="delete">
                            <input type="hidden" name="_token" value="{{csrf_token()}}">
                            <a href="{{route('blog.show',$blog->id)}}" class="btn btn-primary">Show</a>
                            <a href="{{route('blog.edit',$blog->id)}}" class="btn btn-primary">Edit</a>

                            <input type="submit" class="btn btn-danger" onclick="return confirm('Are you sure to delete this data');" name="name" value="delete">



                        </form>
                    </td>
                </tr>
            @endforeach

        </table>
    </div>
    {!! $blogs->links() !!}
@stop

<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 4/21/2017
 * Time: 12:31 AM
 */

resources/views/blog/show.blade.php
@extends('master')
@section('content')
    <div class="form-group row add">
        <div class="col-md-6">

        </div>

    </div>
    <div class="row">
        <h2 style="text-align: center">Single Blog Information</h2>
        <table class="table table-striped">


                <th style="text-align: center"> Title</th>
                <th style="text-align: center" > Description</th>

                <tr>
                    <td style="text-align: center">{{$blog->title}}</td>
                    <td style="text-align: center">{{$blog->description}}</td>
                </tr>

        </table>
        <a href="{{(route('blog.index'))}}" class="btn btn-info pull-left">Back To File</a><br>
    </div>

@stop