routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::group(['middleware' => ['web']], function() {
    Route::resource('blog','BlogController');

});

Route::get('/report', 'BlogController@report');

Route::group(['middleware' => ['web']], function() {
    Route::resource('client','ClientController');
});
Route::group(['middleware' => ['web']], function() {
    Route::resource('newclient','NewclientController');
});


Route::get('image-upload','ImageController@imageUpload');
Route::post('image-upload','ImageController@imageUploadPost');

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    protected $table ='client';
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use App\Client;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *client
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //show Data
        //$clients = Client::all();
        //$clients =DB::table('client')->paginate(5);
        // $clients = Client::paginate(5);
        //return view('client.index',['clients'=>$clients]);
        $search = \Request::get('search');
        $clients = Client::where('clientname','like','%'.$search.'%')->orderBy('id')->paginate(6);
        return view('client.index',['clients' => $clients]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('client.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validation
        $this->validate($request,[
            'clientname'=>'required',
            'organization'=>'required',
            'designation'=>'required',
            'address'=>'required',
            'mobile'=>'required',
            'email'=>'required',
            'auth'=>'required',
            'auth_mobile'=>'required',
            'reference'=>'required',
            'parpose'=>'required',
            'item'=>'required',
            'description'=>'required',
            'requirements'=>'required',
            'domain'=>'required',
            'orderdate'=>'required',
            'renewdate'=>'required',
            'status'=>'required',
            'advance'=>'required',
            'dues'=>'required',
            'cash'=>'required',
            'total'=>'required',
            'cheque'=>'required',
            'chequeno'=>'required',
            'bankname'=>'required',
            'brance'=>'required',
            'statusa'=>'required',


        ]);
        //create new data
        $client = new client;
        $client->clientname=$request->clientname;
        $client->organization=$request->organization;
        $client->designation=$request->designation;
        $client->address=$request->address;
        $client->mobile=$request->mobile;
        $client->email=$request->email;
        $client->auth=$request->auth;
        $client->auth_mobile=$request->auth_mobile;
        $client->reference=$request->reference;
        $client->parpose=$request->parpose;
        $client->item=$request->item;
        $client->description=$request->description;
        $client->requirements=$request->requirements;
        $client->domain=$request->domain;
        $client->orderdate=$request->orderdate;
        $client->renewdate=$request->renewdate;
        $client->status=$request->status;
        $client->advance=$request->advance;
        $client->dues=$request->dues;
        $client->cash=$request->cash;
        $client->total=$request->total;
        $client->cheque=$request->cheque;
        $client->chequeno=$request->chequeno;
        $client->bankname=$request->bankname;
        $client->brance=$request->brance;
        $client->statusa=$request->statusa;
        $client->save();
        return redirect()->route('client.index')->with('alert-success','Data Has Been Save!');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $client = Client::find($id);

        return view('client.show')->with('client',$client);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $client = Client::findOrFail($id);
        return view('client.edit',compact('client'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // validation
        $this->validate($request,[
            'clientname'=>'required',
            'organization'=>'required',
            'designation'=>'required',
            'address'=>'required',
            'mobile'=>'required',
            'email'=>'required',
            'auth'=>'required',
            'auth_mobile'=>'required',
            'reference'=>'required',
            'parpose'=>'required',
            'item'=>'required',
            'description'=>'required',
            'requirements'=>'required',
            'domain'=>'required',
            'orderdate'=>'required',
            'renewdate'=>'required',
            'status'=>'required',
            'advance'=>'required',
            'dues'=>'required',
            'cash'=>'required',
            'total'=>'required',
            'cheque'=>'required',
            'chequeno'=>'required',
            'bankname'=>'required',
            'brance'=>'required',
            'statusa'=>'required',
        ]);

        $client = Client::findOrFail($id);
        $client->clientname=$request->clientname;
        $client->organization=$request->organization;
        $client->designation=$request->designation;
        $client->address=$request->address;
        $client->mobile=$request->mobile;
        $client->email=$request->email;
        $client->auth=$request->auth;
        $client->auth_mobile=$request->auth_mobile;
        $client->reference=$request->reference;
        $client->parpose=$request->parpose;
        $client->item=$request->item;
        $client->description=$request->description;
        $client->requirements=$request->requirements;
        $client->domain=$request->domain;
        $client->orderdate=$request->orderdate;
        $client->renewdate=$request->renewdate;
        $client->status=$request->status;
        $client->advance=$request->advance;
        $client->dues=$request->dues;
        $client->cash=$request->cash;
        $client->total=$request->total;
        $client->cheque=$request->cheque;
        $client->chequeno=$request->chequeno;
        $client->bankname=$request->bankname;
        $client->brance=$request->brance;
        $client->statusa=$request->statusa;
        $client->save();

        return redirect()->route('client.index')->with('alert-success','Data Hasbeen Saved!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //DELETE DATA
        $client = Client::findOrFail($id);
        $client->delete();
        return redirect()->route('client.index')->with('alert-success','Data Has Been Deleted!');

    }
}

resources/views/client/index.blade.php
@extends('master')
@section('content')
    <div class="form-group row add">
        <div class="col-md-6">


        </div>

    </div>
    <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
            <input type="text" name="search" class="form-control" placeholder="search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
    </form>
    <div class="row">
        <h2 style="text-align: center">Client Information</h2>
        <table class="table table-striped">
            <tr>
                <th> No.</th>
                <th> Client Name</th>
                <th> Organization</th>
                <th> Designation</th>
                <th> Address</th>
                <th> Mobile</th>
                <th> Email</th>
                <th> Auth</th>
                <th> Auth_mobile</th>
                <th> Reference</th>
                <th> Parpose</th>
                <th> Item</th>
                <th> Description</th>
                <th> Requirements</th>
                <th> Domain</th>
                <th> Order Date</th>
                <th> Renew Date</th>
                <th> Status</th>
                <th> Advance</th>
                <th> Dues</th>
                <th> Cash</th>
                <th> Total</th>
                <th> Cheque</th>
                <th> Chequeno</th>
                <th> Bankname</th>
                <th> Bank Brance</th>
                <th> Statusa</th>
                <th> Action</th>
            </tr>
            <a href="{{(route('client.create'))}}" class="btn btn-info pull-left">Create New Data</a><br>
            <?php $no=1;?>
            @foreach($clients as $client)
                <tr>
                    <td>{{$no++}}</td>
                    <td>{{$client->clientname}}</td>
                    <td>{{$client->organization}}</td>
                    <td>{{$client->designation}}</td>
                    <td>{{$client->address}}</td>
                    <td>{{$client->mobile}}</td>
                    <td>{{$client->email}}</td>
                    <td>{{$client->auth}}</td>
                    <td>{{$client->auth_mobile}}</td>
                    <td>{{$client->reference}}</td>
                    <td>{{$client->parpose}}</td>
                    <td>{{$client->item}}</td>
                    <td>{{$client->description}}</td>
                    <td>{{$client->requirements}}</td>
                    <td>{{$client->domain}}</td>
                    <td>{{$client->orderdate}}</td>
                    <td>{{$client->renewdate}}</td>
                    <td>{{$client->status}}</td>
                    <td>{{$client->advance}}</td>
                    <td>{{$client->dues}}</td>
                    <td>{{$client->cash}}</td>
                    <td>{{$client->total}}</td>
                    <td>{{$client->cheque}}</td>
                    <td>{{$client->chequeno}}</td>
                    <td>{{$client->bankname}}</td>
                    <td>{{$client->brance}}</td>
                    <td>{{$client->statusa}}</td>

                    <td>
                        <form class="" action="{{route('client.destroy',$client->id)}}" method="post">
                            <input type="hidden" name="_method" value="delete">
                            <input type="hidden" name="_token" value="{{csrf_token()}}">
                            <a href="{{route('client.show',$client->id)}}" class="btn btn-primary">Show</a>
                            <a href="{{route('client.edit',$client->id)}}" class="btn btn-primary">Edit</a>
                            <input type="submit" class="btn btn-danger" onclick="return confirm('Are you sure to delete this data');" name="name" value="delete">



                        </form>
                    </td>
                </tr>
            @endforeach

        </table>
    </div>
      {!! $clients->links() !!}
@stop

resources/views/client/show.blade.php
@extends('master')
@section('content')
    <div class="form-group row add">
        <div class="col-md-6">


        </div>

    </div>

    <div class="row">
        <h2 style="text-align: center">Single Client Information</h2>
        <table class="table table-striped">


            <th> Client Name</th>
            <th> Organization</th>
            <th> Designation</th>
            <th> Address</th>
            <th> Mobile</th>
            <th> Email</th>
            <th> Auth</th>
            <th> Auth_mobile</th>
            <th> Reference</th>
            <th> Parpose</th>
            <th> Item</th>
            <th> Description</th>
            <th> Requirements</th>
            <th> Domain</th>
            <th> Order Date</th>
            <th> Renew Date</th>
            <th> Status</th>
            <th> Advance</th>
            <th> Dues</th>
            <th> Cash</th>
            <th> Total</th>
            <th> Cheque</th>
            <th> Chequeno</th>
            <th> Bankname</th>
            <th> Bank Brance</th>
            <th> Statusa</th>



                <tr>

                    <td>{{$client->clientname}}</td>
                    <td>{{$client->organization}}</td>
                    <td>{{$client->designation}}</td>
                    <td>{{$client->address}}</td>
                    <td>{{$client->mobile}}</td>
                    <td>{{$client->email}}</td>
                    <td>{{$client->auth}}</td>
                    <td>{{$client->auth_mobile}}</td>
                    <td>{{$client->reference}}</td>
                    <td>{{$client->parpose}}</td>
                    <td>{{$client->item}}</td>
                    <td>{{$client->description}}</td>
                    <td>{{$client->requirements}}</td>
                    <td>{{$client->domain}}</td>
                    <td>{{$client->orderdate}}</td>
                    <td>{{$client->renewdate}}</td>
                    <td>{{$client->status}}</td>
                    <td>{{$client->advance}}</td>
                    <td>{{$client->dues}}</td>
                    <td>{{$client->cash}}</td>
                    <td>{{$client->total}}</td>
                    <td>{{$client->cheque}}</td>
                    <td>{{$client->chequeno}}</td>
                    <td>{{$client->bankname}}</td>
                    <td>{{$client->brance}}</td>
                    <td>{{$client->statusa}}</td>

                </tr>


        </table>
        <a href="{{(route('client.index'))}}" class="btn btn-info pull-left">Back To Client</a><br>
    </div>

@stop